/* Nova Verse Academy — main.js */
(function(){"use strict";
const WHATSAPP_NUMBER="201501190654";
const WHATSAPP_DEFAULT_MESSAGE="مرحبًا، أرغب في معرفة تفاصيل مسار Nova Verse Academy وخيارات الاشتراك.";
const WHATSAPP_ICON='<svg class="whatsapp-btn-icon" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12.04 2C6.58 2 2.13 6.45 2.13 11.91c0 1.87.5 3.62 1.44 5.13L2 22l5.13-1.51a9.87 9.87 0 0 0 4.9 1.31h.01c5.46 0 9.91-4.45 9.91-9.91C21.95 6.44 17.5 2 12.04 2Zm0 18.03h-.01a8.17 8.17 0 0 1-4.17-1.14l-.3-.18-3.05.9.9-2.98-.19-.31a8.09 8.09 0 0 1-1.25-4.4c0-4.5 3.66-8.16 8.16-8.16 4.5 0 8.16 3.66 8.16 8.16 0 4.5-3.7 8.11-8.25 8.11Zm4.47-6.11c-.24-.12-1.44-.71-1.66-.79-.22-.08-.39-.12-.55.12-.16.24-.63.79-.78.95-.14.16-.29.18-.53.06-2.07-1.03-3.42-3.08-3.57-3.32-.14-.24-.02-.37.11-.49.25-.24.5-.56.6-.76.08-.16.04-.31-.02-.43-.06-.12-.55-1.32-.75-1.81-.2-.48-.4-.41-.55-.42h-.47c-.16 0-.43.06-.65.31s-.86.84-.86 2.04.88 2.37 1 2.53c.12.16 1.74 2.65 4.21 3.72 2.47 1.06 2.47.71 2.92.67.47-.07 1.44-.59 1.65-1.16.2-.57.2-1.06.14-1.16-.06-.1-.22-.16-.46-.28Z"/></svg>';
function buildWhatsAppLink(message){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message||WHATSAPP_DEFAULT_MESSAGE)}`}
function initWhatsAppLinks(){document.querySelectorAll("[data-whatsapp]").forEach(el=>{el.href=buildWhatsAppLink(el.getAttribute("data-whatsapp-message"));el.target="_blank";el.rel="noopener noreferrer";if(el.classList.contains("btn")&&!el.querySelector(".whatsapp-btn-icon")){el.querySelector(".whatsapp-mini-icon")?.remove();el.insertAdjacentHTML("afterbegin",WHATSAPP_ICON)}})}
function initHeaderScroll(){const h=document.querySelector(".site-header");if(!h)return;const f=()=>h.classList.toggle("is-scrolled",scrollY>24);f();addEventListener("scroll",f,{passive:true})}
function initNavToggle(){const t=document.querySelector(".nav-toggle"),l=document.querySelector(".nav-links");if(!t||!l)return;t.addEventListener("click",()=>{const o=l.classList.toggle("is-open");t.setAttribute("aria-expanded",String(o));document.body.style.overflow=o?"hidden":""});l.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{l.classList.remove("is-open");t.setAttribute("aria-expanded","false");document.body.style.overflow=""}))}
function initScrollReveal(){const ts=document.querySelectorAll(".reveal,.reveal-stagger");if(!("IntersectionObserver"in window)){ts.forEach(t=>t.classList.add("is-visible"));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");o.unobserve(e.target)}}),{threshold:.15,rootMargin:"0px 0px -60px 0px"});ts.forEach(t=>o.observe(t))}
function initTrustDeck(){const deck=document.querySelector("#trust .trust-grid");if(!deck)return;const cards=[...deck.querySelectorAll(".trust-card")];if(cards.length<2)return;let active=0;const dots=document.createElement("div");dots.className="trust-deck-dots";const hint=document.createElement("p");hint.className="trust-deck-hint";hint.textContent=document.documentElement.lang==="ar"?"اسحب لاكتشاف المزيد":"Swipe to discover more";cards.forEach((card,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",`Feature ${i+1}`);b.addEventListener("click",()=>card.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"}));dots.appendChild(b)});deck.after(hint,dots);function paint(index){active=index;cards.forEach((c,i)=>{c.classList.toggle("is-featured",i===index);c.classList.toggle("is-near",Math.abs(i-index)===1)});[...dots.children].forEach((d,i)=>d.classList.toggle("is-active",i===index))}function nearest(){const r=deck.getBoundingClientRect(),center=r.left+r.width/2;let best=0,dist=Infinity;cards.forEach((c,i)=>{const cr=c.getBoundingClientRect(),cc=cr.left+cr.width/2,dd=Math.abs(cc-center);if(dd<dist){dist=dd;best=i}});paint(best)}let raf;deck.addEventListener("scroll",()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(nearest)},{passive:true});cards.forEach((c,i)=>c.addEventListener("click",()=>{if(i!==active)c.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})}));paint(0);requestAnimationFrame(()=>cards[0].scrollIntoView({block:"nearest",inline:"center"}))}
function initStarfield(){const c=document.querySelector(".starfield");if(!c)return;const x=c.getContext("2d");let stars=[],w,h,d;function resize(){d=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;c.style.width=w+"px";c.style.height=h+"px";x.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.floor(w*h/9000)},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.3,o:Math.random()*.6+.25,p:Math.random()*6.28,s:Math.random()*.015+.004}))}function draw(){x.clearRect(0,0,w,h);stars.forEach(a=>{a.p+=a.s;x.beginPath();x.arc(a.x,a.y,a.r,0,6.28);x.fillStyle=`rgba(255,255,255,${a.o*(.6+.4*Math.sin(a.p))})`;x.fill()});requestAnimationFrame(draw)}resize();addEventListener("resize",resize);requestAnimationFrame(draw)}
function initFileLabels(){document.querySelectorAll(".file-upload input[type=file]").forEach(i=>{const l=i.closest(".file-upload")?.querySelector("[data-file-label]");i.addEventListener("change",()=>{if(l)l.textContent=i.files.length?i.files[0].name:"اضغط لاختيار الملف"})})}
document.addEventListener("DOMContentLoaded",()=>{initWhatsAppLinks();initHeaderScroll();initNavToggle();initScrollReveal();initTrustDeck();initStarfield();initFileLabels()});})();