/* Nova Verse Academy — main.js */
(function(){"use strict";
const WHATSAPP_NUMBER="201501190654";
const WHATSAPP_DEFAULT_MESSAGE="مرحبًا، أرغب في معرفة تفاصيل مسار Nova Verse Academy وخيارات الاشتراك.";
function buildWhatsAppLink(message){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message||WHATSAPP_DEFAULT_MESSAGE)}`}
function initWhatsAppLinks(){document.querySelectorAll("[data-whatsapp]").forEach(el=>{el.href=buildWhatsAppLink(el.getAttribute("data-whatsapp-message"));el.target="_blank";el.rel="noopener noreferrer"})}
function initHeaderScroll(){const h=document.querySelector(".site-header");if(!h)return;const f=()=>h.classList.toggle("is-scrolled",scrollY>24);f();addEventListener("scroll",f,{passive:true})}
function initNavToggle(){const t=document.querySelector(".nav-toggle"),l=document.querySelector(".nav-links");if(!t||!l)return;t.addEventListener("click",()=>{const o=l.classList.toggle("is-open");t.setAttribute("aria-expanded",String(o));document.body.style.overflow=o?"hidden":""});l.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{l.classList.remove("is-open");t.setAttribute("aria-expanded","false");document.body.style.overflow=""}))}
function initScrollReveal(){const ts=document.querySelectorAll(".reveal,.reveal-stagger");if(!("IntersectionObserver"in window)){ts.forEach(t=>t.classList.add("is-visible"));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");o.unobserve(e.target)}}),{threshold:.15,rootMargin:"0px 0px -60px 0px"});ts.forEach(t=>o.observe(t))}
function initTrustDeck(){const deck=document.querySelector("#trust .trust-grid");if(!deck)return;const cards=[...deck.querySelectorAll(".trust-card")];if(cards.length<2)return;let active=0;const dots=document.createElement("div");dots.className="trust-deck-dots";const hint=document.createElement("p");hint.className="trust-deck-hint";hint.textContent=document.documentElement.lang==="ar"?"اسحب لاكتشاف المزيد":"Swipe to discover more";cards.forEach((card,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",`Feature ${i+1}`);b.addEventListener("click",()=>card.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"}));dots.appendChild(b)});deck.after(hint,dots);function paint(index){active=index;cards.forEach((c,i)=>{c.classList.toggle("is-featured",i===index);c.classList.toggle("is-near",Math.abs(i-index)===1)});[...dots.children].forEach((d,i)=>d.classList.toggle("is-active",i===index))}function nearest(){const r=deck.getBoundingClientRect(),center=r.left+r.width/2;let best=0,dist=Infinity;cards.forEach((c,i)=>{const cr=c.getBoundingClientRect(),cc=cr.left+cr.width/2,dd=Math.abs(cc-center);if(dd<dist){dist=dd;best=i}});paint(best)}let raf;deck.addEventListener("scroll",()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(nearest)},{passive:true});cards.forEach((c,i)=>c.addEventListener("click",()=>{if(i!==active)c.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})}));paint(0);requestAnimationFrame(()=>cards[0].scrollIntoView({block:"nearest",inline:"center"}))}
function initStarfield(){const c=document.querySelector(".starfield");if(!c)return;const x=c.getContext("2d");let stars=[],w,h,d;function resize(){d=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;c.style.width=w+"px";c.style.height=h+"px";x.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.floor(w*h/9000)},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.3,o:Math.random()*.6+.25,p:Math.random()*6.28,s:Math.random()*.015+.004}))}function draw(){x.clearRect(0,0,w,h);stars.forEach(a=>{a.p+=a.s;x.beginPath();x.arc(a.x,a.y,a.r,0,6.28);x.fillStyle=`rgba(255,255,255,${a.o*(.6+.4*Math.sin(a.p))})`;x.fill()});requestAnimationFrame(draw)}resize();addEventListener("resize",resize);requestAnimationFrame(draw)}
function initFileLabels(){document.querySelectorAll(".file-upload input[type=file]").forEach(i=>{const l=i.closest(".file-upload")?.querySelector("[data-file-label]");i.addEventListener("change",()=>{if(l)l.textContent=i.files.length?i.files[0].name:"اضغط لاختيار الملف"})})}
document.addEventListener("DOMContentLoaded",()=>{initWhatsAppLinks();initHeaderScroll();initNavToggle();initScrollReveal();initTrustDeck();initStarfield();initFileLabels()});})();